from skills.basic_skill import BasicSkill
import sys
import os
import datetime
from io import StringIO

class CaptureTerminalOutputSkill(BasicSkill):
    def __init__(self):
        self.name = "CaptureTerminalOutput"
        self.metadata = {
            "name": self.name,
            "description": "Captures all terminal output up to the point when the skill is invoked and writes it to an autogenerated log file.",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

        # Start capturing stdout and stderr
        self.original_stdout = sys.stdout
        self.original_stderr = sys.stderr
        sys.stdout = self.captured_stdout = StringIO()
        sys.stderr = self.captured_stderr = StringIO()

    def perform(self) -> str:
        """
        Captures the output of the terminal up to this point and exports it to an autogenerated log file.

        Returns:
            str: The result of the skill operation.
        """
        try:
            # Get the captured output
            stdout_content = self.captured_stdout.getvalue()
            stderr_content = self.captured_stderr.getvalue()

            # Restore original stdout and stderr
            sys.stdout = self.original_stdout
            sys.stderr = self.original_stderr

            # Generate a timestamped log filename
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            log_file = f"terminal_output_{timestamp}.log"
            log_file_path = os.path.join("logs", log_file)
            os.makedirs("logs", exist_ok=True)

            # Write the captured output to the log file
            with open(log_file_path, 'w', encoding='utf-8') as file:
                file.write("Captured Standard Output:\n")
                file.write(stdout_content)
                if stderr_content:
                    file.write("\nCaptured Standard Error:\n")
                    file.write(stderr_content)

            return f"Terminal output logged to {log_file_path}"
        except Exception as e:
            return f"An error occurred while executing the CaptureTerminalOutput skill: {str(e)}"
